language: java

jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk6

script :
  - ./gradlew check

env:
  matrix:
  - TERM=dumb

after_success:
  - ./gradlew clean jacocoRootReport coveralls
#  - ./gradlew cobertura coveralls
