language: java

jdk:
  - oraclejdk7
#  - openjdk6

script :
  - ./gradlew check

env:
  matrix:
  - TERM=dumb

after_success:
  - ./gradlew check coveralls
#  - ./gradlew jacocoTestReport coveralls
#  - ./gradlew cobertura coveralls
